import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../features/settings/controllers/settings_controller.dart';

final localizationsProvider = Provider<AppLocalizations>((ref) {
  final lang = ref.watch(settingsControllerProvider).language;
  return AppLocalizations(lang);
});

class AppLocalizations {
  final String language;
  
  AppLocalizations(this.language);

  String get languageKey => language == 'Türkçe' ? 'tr' : 'en';

  String translate(String key) {
    if (languageKey == 'tr') {
      return _tr[key] ?? key;
    } else {
      return _en[key] ?? key;
    }
  }

  static const Map<String, String> _tr = {
    'app_name': 'MasrafBöl',
    'home': 'Anasayfa',
    'all_logs': 'Tüm Kayıtlar',
    'settings': 'Ayarlar',
    'new_expense': 'Harcama Ekle',
    'total_balance': 'TOPLAM BAKİYE',
    'groups': 'Gruplar',
    'new_group': 'Yeni Grup Oluştur',
    'group_name': 'Grup Adı',
    'create': 'Oluştur',
    'expenses': 'harcama',
    'add_member': 'Üye Ekle',
    'close_account': 'Hesabı Kapat',
    'no_expense': 'Henüz harcama yok',
    'paid': 'ödedi',
    'category_general': '📦 Genel',
    'category_food': '🍔 Yemek',
    'category_market': '🛒 Market',
    'category_transport': '🚗 Ulaşım',
    'category_entertainment': '🍿 Eğlence',
    'category_bill': '🧾 Fatura',
    'category_health': '💊 Sağlık',
    'category_education': '📚 Eğitim',
    'category_other': '📝 Diğer',
    'amount': 'TUTAR',
    'what_for': 'Ne için harcandı?',
    'payer': 'ÖDEYEN',
    'split_equal': 'Eşit Böl',
    'split_percent': '% Böl',
    'results': 'Sonuçlar',
    'will_pay': 'ödeyecek',
    'to': 'kişisine',
    'theme': 'Karanlık Tema',
    'currency': 'Para Birimi',
    'app_language': 'Uygulama Dili',
    'clear_data': 'Tüm Verileri Sil',
    'no_group': 'Henüz hiç grubun yok. Yeni bir grup oluşturarak başla!',
    'members': 'üye',
    'my_groups': 'Gruplarım',
    'total_paid': 'Toplam Ödediği:',
    'share_owed': 'Kendi Payına Düşen:',
    'net_status': 'Net Durum:',
    'creditor': 'Alacaklı',
    'debtor': 'Borçlu',
    'calculate': 'Hesapla',
    'tab_personal': 'Gruplar',
    'tab_shared': 'Paylaşımlı',
    'tab_history': 'Kayıtlar',
    'tab_settings': 'Ayarlar',
    'edit': 'Düzenle',
    'delete': 'Kaldır',
    'cancel': 'İptal',
    'delete_user_title': 'Kullanıcıyı Kaldır',
    'delete_user_confirm': 'Bu kullanıcıyı kaldırmak istediğinize emin misiniz?',
    'cannot_delete_member': 'Bu kullanıcı silinemez çünkü harcamalara dahil.',
    'paid_by': 'Ödeyen',
    'settings_general': 'GENEL',
    'settings_data_security': 'VERİ & GÜVENLİK',
    'offline_mode': 'Çevrimdışı Çalışma',
    'offline_mode_desc': 'Tüm veriler cihazınızda tutulur',
    'clear_data_confirm': 'Bu işlem geri alınamaz. Emin misiniz?',
    'delete_expense_confirm': 'Bu harcamayı silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
    'delete_group_confirm': 'Bu grubu ve içindeki tüm harcamaları silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
    'select_category': 'Kategori Seç',
    'date': 'Tarih',
    'total': 'Toplam',
    'add': 'Ekle',
    'expense_add_empty': 'Harcama eklemek için gruba üye eklemelisiniz.',
    'added': 'Eklendi',
    'sort': 'Sırala',
    'sort_newest': 'En Yeniler',
    'sort_oldest': 'En Eskiler',
    'sort_amount_desc': 'Tutar (Yüksek)',
    'sort_amount_asc': 'Tutar (Düşük)',
    'no_expense_log': 'Henüz hiç harcama kaydı yok.',
    'expense_title_default': 'Harcama',
    'share_msg_no_debt': 'Herkesin hesabı eşit, kimsenin borcu yok!',
    'share_msg_results': 'Sonuçları',
    'share_msg_total_expense': 'Toplam Harcama',
    'pdf_report': 'Raporu',
    'pdf_group': 'Grup',
    'pdf_expense_summary': 'Harcama Özeti',
    'pdf_total': 'Toplam',
    'pdf_debt_summary': 'Borç Özeti',
    'pdf_created_with': 'Bu rapor',
    'pdf_created_with_2': 'uygulaması ile oluşturulmuştur.',
    'error': 'Hata',
    'error_loading_data': 'Veriler yüklenirken bir hata oluştu.',
    'unknown': 'Bilinmiyor',
    'who_pays_who': 'Kim Kime Ödeyecek?',
    'share': 'Paylaş',
    'clear_debts': 'Hesabı Sıfırla',
    'clear_debts_soon': 'Hesap sıfırlama yakında eklenecek!',
    'pdf_generation_error': 'PDF oluşturulamadı',
    'sender_debtor': 'Gönderen (Borçlu)',
    'receiver_creditor': 'Alıcı (Alacaklı)',
    'amount_title': 'Tutar',
    'member_name': 'Üye Adı',
    'tagline': 'Hızlı masraf paylaşımı',
    'expense': 'Harcama',
    'Bugün': 'Bugün',
    'Dün': 'Dün',
    'Yarın': 'Yarın',
    'group_name_hint': 'Örn. Yaz Tatili',
    'suggestions': 'ÖNERİLER',
    'category_home': '🏠 Ev',
    'category_holiday': '🏖️ Tatil',
    'category_camp': '⛺ Kamp',
    'category_office': '🏢 Ofis',
    'category_transfer': '💸 Borç / Transfer',
    'Borç / Transfer': '💸 Borç / Transfer',
    'add_transfer': 'Borç / Ödeme Ekle',
    'transfer_save': 'Transferi Kaydet',
    'transfer_edit': 'Değişiklikleri Kaydet',
    'transfer_sender': 'Kim Gönderdi?',
    'transfer_receiver': 'Kime Gönderdi? (Borçlanan)',
    'transfer_desc_hint': 'Örn: Borç ödemesi',
    'transfer_no_member': 'Grupta hiç üye yok.',
    'transfer_invalid_amount': 'Lütfen geçerli bir tutar girin.',
    'total_amount_label': 'Toplam Tutar:',
    'remaining_amount': 'Kalan:',
    'excess_amount': 'Fazla:',
    'distribute_remaining': 'Kalanı Eşit Paylaştır',
    'split_exact_sum_error': 'Girilen tutarların toplamı ana tutara eşit olmalıdır!',
    'split_percent_sum_error': 'Yüzdelerin toplamı tam olarak 100 olmalıdır!',
    'remaining': 'Kalan',
    'excess': 'Fazla',
    'select_one_participant': 'Lütfen en az 1 katılımcı seçin!',
  };

  static const Map<String, String> _en = {
    'app_name': 'Divito',
    'home': 'Home',
    'all_logs': 'All Logs',
    'settings': 'Settings',
    'new_expense': 'Add Expense',
    'total_balance': 'TOTAL BALANCE',
    'groups': 'Groups',
    'new_group': 'Create New Group',
    'group_name': 'Group Name',
    'create': 'Create',
    'expenses': 'expenses',
    'add_member': 'Add Member',
    'close_account': 'Settle Up',
    'no_expense': 'No expenses yet',
    'date': 'Date',
    'total': 'Total',
    'paid': 'paid',
    'category_general': '📦 General',
    'category_food': '🍔 Food',
    'category_market': '🛒 Market',
    'category_transport': '🚗 Transport',
    'category_entertainment': '🍿 Entertainment',
    'category_bill': '🧾 Bill',
    'category_health': '💊 Health',
    'category_education': '📚 Education',
    'category_other': '📝 Other',
    'amount': 'AMOUNT',
    'what_for': 'What was it for?',
    'payer': 'PAYER',
    'split_equal': 'Split Equally',
    'split_percent': 'Split %',
    'results': 'Results',
    'will_pay': 'will pay',
    'to': 'to',
    'theme': 'Dark Theme',
    'currency': 'Currency',
    'app_language': 'App Language',
    'clear_data': 'Clear All Data',
    'no_group': 'You have no groups yet. Start by creating one!',
    'members': 'members',
    'my_groups': 'My Groups',
    'total_paid': 'Total Paid:',
    'share_owed': 'Share Owed:',
    'net_status': 'Net Status:',
    'creditor': 'Creditor',
    'debtor': 'Debtor',
    'calculate': 'Calculate',
    'tab_personal': 'Groups',
    'tab_shared': 'Shared',
    'tab_history': 'History',
    'tab_settings': 'Settings',
    'edit': 'Edit',
    'delete': 'Delete',
    'cancel': 'Cancel',
    'delete_user_title': 'Delete User',
    'delete_user_confirm': 'Are you sure you want to delete this user?',
    'cannot_delete_member': 'This user cannot be deleted because they are part of expenses.',
    'paid_by': 'Paid by',
    'settings_general': 'GENERAL',
    'settings_data_security': 'DATA & SECURITY',
    'offline_mode': 'Offline Mode',
    'offline_mode_desc': 'All data is stored on your device',
    'clear_data_confirm': 'This action cannot be undone. Are you sure?',
    'delete_expense_confirm': 'Are you sure you want to delete this expense? This action cannot be undone.',
    'delete_group_confirm': 'Are you sure you want to delete this group and all its expenses? This action cannot be undone.',
    'select_category': 'Select Category',
    'add': 'Add',
    'expense_add_empty': 'You need to add members to the group to add an expense.',
    'added': 'Added',
    'sort': 'Sort',
    'sort_newest': 'Newest',
    'sort_oldest': 'Oldest',
    'sort_amount_desc': 'Amount (High)',
    'sort_amount_asc': 'Amount (Low)',
    'no_expense_log': 'No expense logs yet.',
    'expense_title_default': 'Expense',
    'share_msg_no_debt': 'Everyone is settled, no debts!',
    'share_msg_results': 'Results',
    'share_msg_total_expense': 'Total Expense',
    'pdf_report': 'Report',
    'pdf_group': 'Group',
    'pdf_expense_summary': 'Expense Summary',
    'pdf_total': 'Total',
    'pdf_debt_summary': 'Debt Summary',
    'pdf_created_with': 'This report was created with the',
    'pdf_created_with_2': 'app.',
    'error': 'Error',
    'error_loading_data': 'An error occurred while loading data.',
    'unknown': 'Unknown',
    'who_pays_who': 'Who Pays Who?',
    'share': 'Share',
    'clear_debts': 'Clear Debts',
    'clear_debts_soon': 'Clearing debts will be added soon!',
    'pdf_generation_error': 'Could not generate PDF',
    'sender_debtor': 'Sender (Debtor)',
    'receiver_creditor': 'Receiver (Creditor)',
    'amount_title': 'Amount',
    'member_name': 'Member Name',
    'tagline': 'Fast expense sharing',
    'expense': 'Expense',
    'Bugün': 'Today',
    'Dün': 'Yesterday',
    'Yarın': 'Tomorrow',
    'group_name_hint': 'E.g. Summer Vacation',
    'suggestions': 'SUGGESTIONS',
    'category_home': '🏠 Home',
    'category_holiday': '🏖️ Holiday',
    'category_camp': '⛺ Camp',
    'category_office': '🏢 Office',
    'category_transfer': '💸 Debt / Transfer',
    'Borç / Transfer': '💸 Debt / Transfer',
    'add_transfer': 'Add Debt / Payment',
    'transfer_save': 'Save Transfer',
    'transfer_edit': 'Save Changes',
    'transfer_sender': 'Who Sent?',
    'transfer_receiver': 'To Whom? (Debtor)',
    'transfer_desc_hint': 'E.g. Debt payment',
    'transfer_no_member': 'No members in the group.',
    'transfer_invalid_amount': 'Please enter a valid amount.',
    'total_amount_label': 'Total Amount:',
    'remaining_amount': 'Remaining:',
    'excess_amount': 'Excess:',
    'distribute_remaining': 'Distribute Remaining',
    'split_exact_sum_error': 'The sum of entered amounts must equal the total amount!',
    'split_percent_sum_error': 'The sum of percentages must be exactly 100!',
    'remaining': 'Remaining',
    'excess': 'Excess',
    'select_one_participant': 'Please select at least 1 participant!',
    // Backward compatibility for old DB entries
    'Genel': 'General',
    'Yemek': 'Food',
    'Market': 'Market',
    'Ulaşım': 'Transport',
    'Eğlence': 'Entertainment',
    'Fatura': 'Bill',
    'Sağlık': 'Health',
    'Eğitim': 'Education',
    'Diğer': 'Other',
  };
}
